name: CI

on: [push, pull_request]

jobs:
  test-api:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install (editable)
        run: |
          pip install -e ".[test]"

      - name: Sync RFCs & Build index
        run: |
          bash scripts/sync_rfc_min.sh
          python scripts/build_index.py

      - name: Start API (8001)
        env:
          AE_INDEX_DIR: ${{ github.workspace }}/data/index
          AE_BIND_PORT: 8001
        run: |
          python -m ae2.api.main & 
          echo $! > api.pid
          sleep 3

      - name: Smoke tests
        run: |
          curl -s http://localhost:8001/healthz | jq .
          curl -s "http://localhost:8001/debug/explain?query=what%20is%20ospf" | jq .
          curl -s -X POST http://localhost:8001/query \
               -H "Content-Type: application/json" \
               -d '{"query":"What is OSPF?","top_k":3}' | jq .

      - name: Stop API
        if: always()
        run: |
          kill $(cat api.pid) || true 